### ISSUE TITLE
Diagnose and fix revdep checks.

### ISSUE THREAD

**Issue by krivit** [statnet/network#57]
The results are at https://github.com/statnet/network/tree/master/revdep, and they are not great.

**Comment by knapply** [comment]
These almost all seem related to `{purrr}` missing -- which `{network}` doesn't use.  Figuring out what's relying on `{purrr}` and why it's not getting installed as a dependency would remove most of them. 

The others seem mainly due to reliance on pre-`as.network.data.frame()` behavior: `as.network.default()` calls `as.network.matrix()` explicitly instead of using S3 dispatch (discussed [here](https://github.com/statnet/network/pull/20#issuecomment-564830962)).  Examples in these packages are just passing `data.frame`s instead of `matrix`es.  The error is being caught because `as.network.data.frame()` is strict and requires `loops = TRUE` if your data frame has them.

- `{purrr}` isn't found:
  + `{bingat}`
  + `{EloRating}`
  + `{haplotypes}`
  + `{ICON}`
  + `{mpa}` (also has other issues unrelated to `{network}`)
  + `{netdiffuseR}`
  + `{nethet}` (also has other issues unrelated to `{network}`)
  + `{networkABC}`
  + `{NetworkDistance}`
  + `{networkDynamic}` (also has issues with S3 consistency)
  + `{networkDynamicData}`
  + `{networksis}` (also has issues with iffy NAMESPACE)
  + `{PAFit}`
  + `{PDN}`
  + `{sna}`
  + `{SparseTSCGM}`

- `as.network.data.frame()` breaks old behavior
  + `{discourseGT}`
  + `{geomnet}`
  + `{GGally}`

- I can't tell yet:
  + `{GOxploreR}` (seems like a malformed data frame issue unrelated to `{network}`)

**Comment by martinamorris** [comment]
thx @knapply -- i don't understand that `purrr` error, as the `purrr` package is not referenced by `network` anywhere.  do you know what that could be referring to?

**Comment by knapply** [comment]
It looks like `{network}` imports `{statnet.common}`, which imports `{purrr}`.  The GitHub version of `{statnet.common}`'s [`DESCRIPTION`](https://github.com/statnet/statnet.common/blob/d281c24d57e91854373ab57c1ba5d2d7e2ec16f7/DESCRIPTION#L10) has `{purrr}` listed, but the [CRAN version](https://cran.r-project.org/web/packages/statnet.common/index.html) does not -- so my best guess (only browsing GitHub) is that it's related to that.

**Comment by martinamorris** [comment]
very helpful, thx.

@Pavel, is it possible to release an update of  `statnet.common` now?  Or would that break current CRAN statnet packages?

**Comment by krivit** [comment]
I wonder if it might be simpler to just remove the dependency on `purrr` from `statnet.common`, since it doesn't look like it's being used for anything particularly complex.

**Comment by krivit** [comment]
OK, `statnet.common` no longer uses `purrr`. Can someone please rerun some of these checks to see if there is still a problem?

**Comment by martinamorris** [comment]
started

**Comment by knapply** [comment]
@martinamorris, is there a statnet.org email I can CC on that?

`geomnet `and `GGally` are developed via GitHub, so I'll see if a quick PR can resolve the issue when I can get to it -- hopefully this week.

**Comment by martinamorris** [comment]
> @martinamorris, is there a statnet.org email I can CC on that?

no, but your q got the discussion going.  for now just cc: me:  morrism@uw.edu

**Comment by krivit** [comment]
In the interests of making the transition smoother, can we have loops issue fire a deprecation warning instead, including that it will be an error in the next release?

**Comment by krivit** [comment]
From what I am seeing in the [`loops-warn` branch checks](https://github.com/statnet/network/tree/loops-warn/revdep), it's not *just* the loops issue for those packages.

**Comment by krivit** [comment]
Also, I am getting an error from `Blaunet` as well. @martinamorris , @knapply , can you reproduce?

**Comment by krivit** [comment]
Reran the [checks on `master`](https://github.com/statnet/network/tree/master/revdep ); indeed, `Blaunet` is showing up.

I guess the fix we could suggest is to wrap their arguments to `as.network()` in `as.matrix()`.

**Comment by krivit** [comment]
@knapply , have you contacted those developers?

As a stopgap, I am considering wrapping the `as.data.frame.network()`'s contents in `try()`, and on some specific errors, falling back to the `as.matrix()` method after firing a deprecation warning.

**Comment by krivit** [comment]
Well, that fixed 2 out of 4 https://github.com/statnet/network/tree/as.df_try/revdep . I guess we'll just have to let the package authors know and hope for the best.

**Comment by krivit** [comment]
We did what we could.
