### ISSUE TITLE
mixingmatrix function -- why is it in network?

### ISSUE THREAD

**Issue by martinamorris** [statnet/network#7]
IIRC this function was originally in `ergm`, and was moved to `network`.  

i think of mixingmatrix as a network descriptive, so the natural place for it would be `sna`.  is there a reason it was moved to `network` instead?

**Comment by krivit** [comment]
Looking at `statnet_dev`, @CarterButts moved moved it there 2010 so that `summary.network()` could print mixing matrices.

**Comment by krivit** [comment]
I'm closing this for now; if anyone wants to continue the discussion, please reopen.

**Comment by CarterButts** [comment]
Yes, I think it is correct that it was moved for this reason.  I no longer remember, but I think there was some specific problem that necessitated it being moved out of ergm (where I think it was) to network.  Probably, it involved CRAN cracking down on cross-package dependencies, though I might be wrong.  Anyway, at present it makes sense for it to be in network, since it can be viewed as a type of relatively primitive data display/coercion tool.  It sits somewhere in the uncanny valley between pure data conversion/summary and analysis, but since its functionality is closely tied to network, it's reasonable enough to put it on the former side of the line.

**Comment by krivit** [comment]
Carter, did you mean to reopen this?

**Comment by CarterButts** [comment]
Yes, because I came across an email of Martina's that asked about it, and that I'd forgotten to respond to.  But now I'll close the issue again.  :-)
