### ISSUE TITLE
Remove is.network() checks from *.network methods?

### ISSUE THREAD

**Issue by krivit** [statnet/network#89]
For example, here:

https://github.com/statnet/network/blob/ddda8d6213a03384d3e6c48478830bf1890d16d3/R/access.R#L274-L278

Since this is already dispatched when `x` is a `network`, with an error raised if the generic is called for an unimplemented class, this code doesn't actually do anything.

**Comment by CarterButts** [comment]
Having these checks is insurance against someone directly calling `add.vertices.network` or the like with something other than a network object; given that some of these functions end up calling backend routines, it's a good idea to directly verify that they were called with network objects rather than count on dispatching.  The checks should also be pretty cheap, and these are not functions that are usually called in bulk.  I'm thus disinclined to remove these checks, at least unless we have evidence that they are causing a problem.
