### ISSUE TITLE
Network package's dependencies

### ISSUE THREAD

**Issue by krivit** [statnet/network#9]
Splitting out the discussion in #3 , the version of network on CRAN depends on libraries that come with R (`utils`, `stats`, `graphics`, etc.).

The version in `master` also imports `tibble`, which, in turn, imports `rlang` and others.

So, we need to decide wither we
1. Keep dependencies limited to baseline R. This means `as_tibble.network()` and related should be changed to `data.frame()` methods.
2. Allow `rlang`, `tibble`, and similar low-level dependencies.

As I see it, the arguments for Option 1 is
* Faster installation and/or load times, if `network` is the only one package in use that uses Tidyverse.
* Less chance of breakage if some change is made to a dependency.

The arguments for Option 2 are
* `data.frame` requires a lot of care to keep from mangling things like non-atomic edge attributes, hypergraph edgelists, etc..
* `tibble` has over 400 packages depending on it directly in some form (and many more indirectly), so it is increasingly unlikely that no other package on a given system will depend on `tibble`.

My preference is Option 2, but I know others differ.

@CarterButts, @martinamorris, @knapply, @skyebend, any thoughts?

**Comment by CarterButts** [comment]
I'm pretty negative about creating dependencies of our core data management infrastructure on packages that (1) we don't control and (2) aren't part of the R core.  What happens when the "tibble" people decide to mess with their data structure?  When they abandon the package?  In my view, we should never have gone down the road of using such things in our low-level toolkits - we should depend on core R tools, and nothing else, unless there is really no alternative.  (Insert rant about how runaway dependencies are an increasing problem in R more generally.  There's a lot of short-sighted design that doesn't take into account the fact that code needs to be reusable for decades.....)

But in the end, the question is whether statnet as a whole is going to accept these dependencies as inevitable.  If that's where the development is going to go, then there's no real point in not using them throughout.  (Or to be more precise, if we're going to be at a point where essentially all of our packages are going to need them anyway, then there's not much to be gained by keeping them out of the low-level stuff.)  However, if this is a fad thing, where today folks are infatuated with package X and tomorrow they'll have shifted to package Y, then we should absolutely steer clear.  We have very limited code maintenance bandwidth, so do not have the luxury of retooling every time that the "data science" fankids decide that some library or other is the bees knees.  Keeping our dependencies minimal keeps those sorts of costs to a minimum.  (Dealing with CRAN's own shifting demands is bad enough, frankly.)

So are we committing our entire toolchain to tibble et al., forever more?  If so, we update the dependencies accordingly.  If not, we need to keep the dependencies minimal.

**Comment by martinamorris** [comment]
Thanks Carter,

I get your point about dependencies, and agree this needs to be thought 
through. So...

I don't think the Tibble is a fad, and i can also imagine a situation 
where it changes in the future -- but more in the way that base R also 
changes over time.

I think there's a secular shift in R ecosystem for dealing with data 
management, based on the tidyverse tools.  Having used them, I have to say 
they're an improvement for most users, and I suspect they will become the 
standard set of tools learned by most people who use R for data analysis 
purposes (not sure about the statistical methodology development folks, 
but Pavel seems to have made the switch).  All of which suggests that 
Tibble is here to stay, and there will be a lot of pressure for 
stability, since it is a foundational data structre.

So, if Pavel finds it useful to make the change, I'm not opposed.

On Fri, 4 Jan 2019, CarterButts wrote:

> 
> I'm pretty negative about creating dependencies of our core data management infrastructure on packages that (1) we don't
> control and (2) aren't part of the R core. What happens when the "tibble" people decide to mess with their data
> structure? When they abandon the package? In my view, we should never have gone down the road of using such things in our
> low-level toolkits - we should depend on core R tools, and nothing else, unless there is really no alternative. (Insert
> rant about how runaway dependencies are an increasing problem in R more generally. There's a lot of short-sighted design
> that doesn't take into account the fact that code needs to be reusable for decades.....)
> 
> But in the end, the question is whether statnet as a whole is going to accept these dependencies as inevitable. If that's
> where the development is going to go, then there's no real point in not using them throughout. (Or to be more precise, if
> we're going to be at a point where essentially all of our packages are going to need them anyway, then there's not much
> to be gained by keeping them out of the low-level stuff.) However, if this is a fad thing, where today folks are
> infatuated with package X and tomorrow they'll have shifted to package Y, then we should absolutely steer clear. We have
> very limited code maintenance bandwidth, so do not have the luxury of retooling every time that the "data science"
> fankids decide that some library or other is the bees knees. Keeping our dependencies minimal keeps those sorts of costs
> to a minimum. (Dealing with CRAN's own shifting demands is bad enough, frankly.)
> 
> So are we committing our entire toolchain to tibble et al., forever more? If so, we update the dependencies accordingly.
> If not, we need to keep the dependencies minimal.
> 
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the
> thread.[AH0J4k9GuxEdNlaARuJJUARZgaFGMW1mks5u_-8KgaJpZM4ZpVMj.gif]
> 
> 
>

****************************************************************
  Professor of Sociology and Statistics
  Director, UWCFAR Sociobehavioral and Prevention Research Core
  Box 354322
  University of Washington
  Seattle, WA 98195-4322

  Office:        (206) 685-3402
  Dept Office:   (206) 543-5882, 543-7237
  Fax:           (206) 685-7419

morrism@u.washington.edu
http://faculty.washington.edu/morrism/

**Comment by CarterButts** [comment]
That's not unreasonable, assuming that other indications also suggest that the packages are likely to be stable.  And assuming that we're not adding tons of cruft.  Fear the cruft, for it drageth ye down into dark waters, where ye shall drown.

Being myself so far untidy, I am unable to judge the virtues of incorporating this into our toolchain.  I also do not use RStudio, edit my HTML by hand, and drive a stick shift, however, so my preferences are undoubtedly more austere than those of the masses.  If you are convinced that this is really going to be worth it down the road, then I will acquiesce.

**Comment by krivit** [comment]
My hope is that this will reduce the amount of cruft in our case, because a lot of what Tidyverse's utilities do is automate common patterns and generally make things like outputs more predictable.

**Comment by CarterButts** [comment]
Tell me that they implement real data structures with R-level interfaces (balanced trees or skip lists, single/double linked lists, etc.) and I shall become a convert.  I wrote a dark arts version of such a thing long ago, but it wasn't what you would call safe or sane.  Every now and again I'm tempted to go write a more trustworthy package for that, but then I have a grant proposal that I end up writing instead.  Alas.

OK, so what's the state of play?  Is the version in master tested and ready to go, or does something else need to be done to avoid drawing the ire of the R gods (and/or actually breaking something)?

**Comment by krivit** [comment]
> Tell me that they implement real data structures with R-level interfaces (balanced trees or skip lists, single/double linked lists, etc.) and I shall become a convert.

I think Rcpp might enable something like that to be implemented pretty easily.

> OK, so what's the state of play? Is the version in master tested and ready to go, or does something else need to be done to avoid drawing the ire of the R gods (and/or actually breaking something)?

As far as I can tell, it's ready to go. There are issues, that I've tagged with the 1.14 milestone, that we should either resolve or postpone until the next release.

**Comment by knapply** [comment]
The tidyverse's influence can't really be ignored and it's definitely not going away. Case in point: much of R's spatial ecosystem has been rebuilt over the last few years to use `sf` as the core vector geometry package. `sf` was intentionally built to be a tidy-compliant replacement for `sp` after data frame list columns were declared "tidy".

Personally, I can't imagine going back to base R for plotting or data carpentry. The difference in productivity is staggering. Even Python Pandas has move toward a tidyverse-style method-chaining approach that is deprecating in-place modifications.

All that said, the tidyverse is still evolving and I think overindulging should be avoided. `rlang` is not 100% stable and they explicitly warn that it's still maturing. There are also several core packages that have not yet reached 1.0 (`dplyr`, `purrr`, and `tidyr`).

I also want to point out that `sf` is intentionally "tidy" compliant, but does so without depending on the tidyverse (outside of re-exporting magrittr's pipe for user convenience). If I want `dplyr`-style data manipulation, I can do that. If I want to use faster `data.table` methods, I can do that too. But... I don't need either and neither can break `sf`'s functionality.

It's doubtful any changes will effect `tibble` construction as one of its goals is to avoid the lack of safety in `base::data.frame()`, but I also demonstrated that the dependency is avoidable. If something were to ever go wrong, there's a backup that has some obvious refinements I can make.

I want to contribute, but I didn't see the sense in refining that code and making a pull request without nailing down specifics.

Since you're moving ahead with the tidy approach, it would be useful to re-export `as_tibble.network()`.

@CarterButts , if I correctly understand what you're describing regarding real data structures, I agree with @krivit that Rcpp is more what you're after.

Here's an example using an Rcpp module that may give you some ideas:

<details>
  <summary>Rcpp example</summary>

<br>

Define a C++ class with some member functions:

``` cpp
// .cpp file
#include <Rcpp.h>

class Counter {
private:    
  // the STL container can obviously be swapped...
  std::map<int, int> counts; // I'm almost positive GCC implements std::map as a red-black tree
public:
  Rcpp::IntegerVector original_input;
  
  Counter(const Rcpp::IntegerVector& x) {
    this->original_input = x;
    for (int i = 0; i < x.size(); i++) {
      this->counts[ x[i] ]++;
    }
  }
  
  std::map<int, int> get_counts() { 
    return this->counts; 
  }
  
  void add_value(const int& x) {
    counts[x]++;
  }
};
```

Create a module to define access from R.

``` cpp
// still .cpp file
RCPP_MODULE(Counter) {
  Rcpp::class_<Counter>("CPPCounter")
  .constructor<Rcpp::IntegerVector>()
  .field("original_input",         &Counter::original_input)
  .method("get_counts",            &Counter::get_counts)
  .method("add_value",             &Counter::add_value)
  ;
}

```

Take it for a spin.

``` r
# .R
set.seed(8675309)
( input <- sample(1:3, size = 20, replace = TRUE) )
#>  [1] 1 2 3 3 1 3 3 3 3 2 3 2 2 1 3 3 3 1 3 3

( cpp_counter <- new(Class = CPPCounter, input) )
#>  C++ object <0x560bda755b60> of class 'CPPCounter' <0x560bdf790930>

cpp_counter$original_input
#>  [1] 1 2 3 3 1 3 3 3 3 2 3 2 2 1 3 3 3 1 3 3

cpp_counter$get_counts()
#>  1  2  3 
#>  4  4 12 

cpp_counter$add_value(4)

cpp_counter$get_counts()
#>  1  2  3  4 
#>  4  4 12  1 

```
</details>

**Comment by krivit** [comment]
@knapply , so we want to avoid depending on `purrr`? I'm using it for the `%>%`, `map()`, and `set_names()` in `as_tibble.network()`, but all those are easily replaced.

**Comment by knapply** [comment]
@krivit Yes. They're easy to replace and you're not sacrificing with just because those are easier to swap and you're not sacrificing performance. I love `purrr`,  unless you're using  `map_df` `purrr` for things like  is phenomenal

**Comment by knapply** [comment]
@krivit `set_names()` is re-exported from `purrr`, but is defined in `rlang`, so that can be kept. I would drop `map()` and `%>%`.

I am very fond of `purrr` (type-safety, formulas as lambdas) but unless you're using it in areas where base R doesn't really cut it (`transpose()`) or want type-safe mappers using multiple inputs (replacing `Map()` or `mapply()`) it's probably not worth depending on it in a package.

**Comment by krivit** [comment]
Now that I look, they are all in `magrittr`, so I'll switch to that.

**Comment by krivit** [comment]
Anyway, it sounds like we have a semblance of a consensus: infrastructure dependencies are allowed, but be conservative. I'll close this issue.

**Comment by martinamorris** [comment]
Thanks for your input @knapply -- looks like you're doing some interesting work we should know about :)

**Comment by skyebend** [comment]
Can we base the decision on if we should depend on a package on some sort of centrality score, rather than raw indegree?   (joke, joke :-)     Dependency creep can be a real problem,  but my impression is that if the tidyverse breaks, re-releasing a version of network to remove the dependencies might easier for us than the rest of the R ecosystem.
